services:
    mariadb:
        env_file: ".env"
        image: requirements/mariadb
        build: ./requirements/mariadb
        networks:
            - isolated
        volumes:
            - db-data:/var/lib/mysql
        secrets:
            - db_password
        restart: unless-stopped
    nginx:
        env_file: ".env"
        depends_on:
            - wordpress
        image: requirements/nginx
        build: ./requirements/nginx
        networks:
            - isolated
        volumes:
            - wp-data:/var/www/html
        ports:
            - "443:443"
        restart: unless-stopped
    wordpress:
        depends_on:
            - mariadb
        env_file: ".env"
        image: requirements/wordpress
        build: ./requirements/wordpress
        networks:
            - isolated
        volumes:
            - wp-data:/var/www/html
        secrets:
            - db_password
            - wp_password
            - wp_password2
        restart: unless-stopped
    static:
        build: ./requirements/bonus/static
        networks:
            - isolated
        ports:
            - "8080:8080"
        restart: unless-stopped
    adminer:
        build: ./requirements/bonus/adminer
        networks:
            - isolated
        ports:
            - "8081:8081"
        restart: unless-stopped
    ftp:
        env_file: ".env"
        build: ./requirements/bonus/ftp
        networks:
            - isolated
        volumes:
            - wp-data:/var/www/html
        ports:
            - "21:21"
            - "10090-10100:10090-10100"
        secrets:
            - ftp_password
        restart: unless-stopped
    redis:
        build: ./requirements/bonus/redis
        networks:
            - isolated
        ports:
            - "6379:6379"
        restart: unless-stopped
    netdata:
        build: ./requirements/bonus/netdata
        networks:
            - isolated
        ports:
            - "19999:19999"
        restart: unless-stopped

networks:
    isolated:
        driver: bridge

secrets:
    db_password:
        file: ../secrets/db_password.txt
    wp_password:
        file: ../secrets/wp_password.txt
    wp_password2:
        file: ../secrets/wp_password2.txt
    ftp_password:
        file: ../secrets/ftp_password.txt

volumes:
    db-data:
        driver: local
        driver_opts:
            type: none
            device: /tmp/data/mariadb
            o: bind
    wp-data:
        driver: local
        driver_opts:
            type: none
            device: /tmp/data/wordpress
            o: bind
